const en = {
"<p>If your are an affilated player you can buy the book 100 years of Belgianchess history for the low price of 10 Euro. Non affilated persons can buy the book for 15 Euro.</p> <p>The book is available in 3 languages:  Dutch, French and German.</p><p>If you are an affiliated player, don't forget to provide your RBCF ID and to click on the search button.  Your name will be filled in automatically</p>": "<p>If your are an affilated player you can buy the book 100 years of Belgianchess history for the low price of 10 Euro. Non affilated persons can buy the book for 15 Euro.</p> <p>The book is available in 3 languages:  Dutch, French and German.</p><p>If you are an affiliated player, don't forget to provide your RBCF ID and to click on the search button.  Your name will be filled in automatically</p>",
"<p>In a few minutes you will receive an confirmation e-mail for your order.The e-mail will include the payment instructions.</p><p>If you selected one of the board members for the delivery, you will find the contact details in this e-mail.</p>": "<p>In a few minutes you will receive an confirmation e-mail for your order.The e-mail will include the payment instructions.</p><p>If you selected one of the board members for the delivery, you will find the contact details in this e-mail.</p>",
"<p>In order to keep the costs low, you can pick the books from 1 of the 7 people listed below.</p><ul><li>Luc Cornet, covering provinces of Limburg and Liège<li>Bernard Malfliet, covering provinces of Oost-Vlaanderen and Vlaams Brabant<li>Ruben Decrop, covering provinces of Antwerpen and West-Vlaanderen<li>Philippe Vukojevic, covering provinces of Namur and Luxembourg<li>Laurent Wery, covering provinces of Hainaut and Brabant Wallon<li>Günter Delhaes, covering the German speaking region, reachable at <a href='mailto:delhaes.g@skynet.be'>delhaes.g@skynet.be</a><li>Frank Hoffmeister, covering Brussels, reachable at <a href='mailto:Frank.HOFFMEISTER@ec.europa.eu'>Frank.HOFFMEISTER@ec.europa.eu</a></ul><p>You have to contact that person and agree on where and when the book can be handed over.  See the <a href='/page/board'>Board page</a> for the contact details of the board members.</p> <p>Alternatively we can deliver the book at any address in Belgium by DPD at an additional cost of 6.20 Euro </p>": "<p>In order to keep the costs low, you can pick the books from 1 of the 7 people listed below.</p><ul><li>Luc Cornet, covering provinces of Limburg and Liège<li>Bernard Malfliet, covering provinces of Oost-Vlaanderen and Vlaams Brabant<li>Ruben Decrop, covering provinces of Antwerpen and West-Vlaanderen<li>Philippe Vukojevic, covering provinces of Namur and Luxembourg<li>Laurent Wery, covering provinces of Hainaut and Brabant Wallon<li>Günter Delhaes, covering the German speaking region, reachable at <a href='mailto:delhaes.g@skynet.be'>delhaes.g@skynet.be</a><li>Frank Hoffmeister, covering Brussels, reachable at <a href='mailto:Frank.HOFFMEISTER@ec.europa.eu'>Frank.HOFFMEISTER@ec.europa.eu</a></ul><p>You have to contact that person and agree on where and when the book can be handed over.  See the <a href='/page/board'>Board page</a> for the contact details of the board members.</p> <p>Alternatively we can deliver the book at any address in Belgium by DPD at an additional cost of 6.20 Euro </p>",
"Address": "Address",
"Administration": "Administration",
"BC Adults": "BC Adults",
"BC Blitz": "BC Blitz",
"BC Rapid": "BC Rapid",
"BC School chess": "BC School chess",
"BC Youth": "BC Youth",
"Board": "Board",
"Board members": "Board members",
"Book 100 years": "Book 100 years",
"Chess equiment": "Chess equiment",
"Committees": "Committees",
"Competitions": "Competitions",
"Confirm": "Confirm",
"Contact details": "Contact details",
"Cost": "Cost",
"Delivery": "Delivery",
"Distribution points": "Distribution points",
"Dutch": "Dutch",
"E-mail": "E-mail",
"ELO processing": "ELO processing",
"ELO tournaments": "ELO tournaments",
"Email addresses": "Email addresses",
"First name": "First name",
"French": "French",
"GDPR": "GDPR",
"G License": "G License",
"German": "German",
"Home": "Home",
"ID RBCF": "ID RBCF",
"Identity": "Identity",
"Internal rules": "Internal rules",
"International": "International",
"International competitions": "International competitions",
"Last name": "Last name",
"Mandated persons": "Mandated persons",
"Mobile phone": "Mobile phone",
"Order created successfully": "Order created successfully",
"Ordering form": "Ordering form",
"Ordering the book 100 years of Belgian chess history": "Ordering the book 100 years of Belgian chess history",
"Postal address": "Postal address",
"Questions": "Questions",
"read more": "read more",
"Regional": "Regional",
"Registered office": "Registered office",
"Reports": "Reports",
"Results SWAR": "Results SWAR",
"Royal Belgian Chess Federation npo": "Royal Belgian Chess Federation npo",
"Social media": "Social media",
"Statutes": "Statutes",
"Tools": "Tools",
"Tournament rules": "Tournament rules",
"Useful information": "Useful information",
"Which versions do you want?": "Which versions do you want?",
"Youth": "Youth",
}
export default en