const en = {
"Administration": "Administration",
"BC Adults": "BC Adults",
"BC Blitz": "BC Blitz",
"BC Rapid": "BC Rapid",
"BC School chess": "BC School chess",
"BC Youth": "BC Youth",
"Board": "Board",
"Chess equiment": "Chess equiment",
"Committees": "Committees",
"Competitions": "Competitions",
"ELO processing": "ELO processing",
"Email addresses": "Email addresses",
"G License": "G License",
"Home": "Home",
"Internal rules": "Internal rules",
"International": "International",
"International competitions": "International competitions",
"read more": "read more",
"Regional": "Regional",
"Reports": "Reports",
"Results SWAR": "Results SWAR",
"Statutes": "Statutes",
"Tools": "Tools",
"Tournament rules": "Tournament rules",
"Useful information": "Useful information",
"Youth": "Youth",
}
export default en