const en = {
"<p>If your are an affilated player you can buy the book 100 years of Belgianchess history for the low price of 10 Euro. Non affilated persons can buy the book for 15 Euro.</p> <p>The book is available in 3 languages:  Dutch, French and German.</p><p>If you are an affiliated player, don't forget to provide your RBCF ID and to click on the search button.  Your name will be filled in automatically</p>": "<p>If your are an affilated player you can buy the book 100 years of Belgianchess history for the low price of 10 Euro. Non affilated persons can buy the book for 15 Euro.</p> <p>The book is available in 3 languages:  Dutch, French and German.</p><p>If you are an affiliated player, don't forget to provide your RBCF ID and to click on the search button.  Your name will be filled in automatically</p>",
"<p>In a few minutes you will receive an confirmation e-mail for your order.The e-mail will include the payment instructions.</p><p>If you selected one of the board members for the delivery, you will find the contact details in this e-mail.</p>": "<p>In a few minutes you will receive an confirmation e-mail for your order.The e-mail will include the payment instructions.</p><p>If you selected one of the board members for the delivery, you will find the contact details in this e-mail.</p>",
"<p>In order to keep the costs low, you can pick the books from 5 members of the board.  You have to contact that person and agree on where and when the book can be handed over.</p><p>The board members are:</p><ul><li>Luc Cornet, covering provinces of Limburg and Liège<li>Bernard Malfliet, covering provinces of Oost-Vlaanderen cost, and Vlaams Brabant<li>Ruben Decrop, covering provinces of Antwerp and West-Vlaanderen<li>Philippe Vukojevic, covering provinces of Namur and Luxembourg<li>Laurent Wery, covering Brussels and provinces of Hainaut and Brabant Wallon</ul><p>See the <a href='/page/board'>Board page</a> for the contact details.</p> <p>Alternatively we can deliver the book at any address in Belgium by DPD at an additional cost of 6.20 Euro </p>": "<p>In order to keep the costs low, you can pick the books from 5 members of the board.  You have to contact that person and agree on where and when the book can be handed over.</p><p>The board members are:</p><ul><li>Luc Cornet, covering provinces of Limburg and Liège<li>Bernard Malfliet, covering provinces of Oost-Vlaanderen cost, and Vlaams Brabant<li>Ruben Decrop, covering provinces of Antwerp and West-Vlaanderen<li>Philippe Vukojevic, covering provinces of Namur and Luxembourg<li>Laurent Wery, covering Brussels and provinces of Hainaut and Brabant Wallon</ul><p>See the <a href='/page/board'>Board page</a> for the contact details.</p> <p>Alternatively we can deliver the book at any address in Belgium by DPD at an additional cost of 6.20 Euro </p>",
"Address": "Address",
"Administration": "Administration",
"BC Adults": "BC Adults",
"BC Blitz": "BC Blitz",
"BC Rapid": "BC Rapid",
"BC School chess": "BC School chess",
"BC Youth": "BC Youth",
"Board": "Board",
"Board members": "Board members",
"Chess equiment": "Chess equiment",
"Committees": "Committees",
"Competitions": "Competitions",
"Confirm": "Confirm",
"Contact details": "Contact details",
"Cost": "Cost",
"Delivery": "Delivery",
"Distribution points": "Distribution points",
"Dutch": "Dutch",
"E-mail": "E-mail",
"ELO processing": "ELO processing",
"Email addresses": "Email addresses",
"First name": "First name",
"French": "French",
"G License": "G License",
"German": "Französisch",
"Home": "Home",
"ID RBCF": "ID RBCF",
"Identity": "Identity",
"Internal rules": "Internal rules",
"International": "International",
"International competitions": "International competitions",
"Last name": "Last name",
"Mandated persons": "Mandated persons",
"Mobile phone": "Mobile phone",
"Ordering form": "Ordering form",
"Ordering the book 100 years of Belgian chess history": "Ordering the book 100 years of Belgian chess history",
"read more": "read more",
"Regional": "Regional",
"Reports": "Reports",
"Results SWAR": "Results SWAR",
"Statutes": "Statutes",
"Tools": "Tools",
"Tournament rules": "Tournament rules",
"Useful information": "Useful information",
"Which versions do you want?": "Which versions do you want?",
"Youth": "Youth",
}
export default en