const fr = {
"Administration": "Administration",
"BC Adults": "CB adultes",
"BC Blitz": "CB Blitz",
"BC Rapid": "CB Rapid",
"BC School chess": "BK inter-écoles",
"BC Youth": "CB Jeunesse",
"Board": "Organe d'administration",
"Chess equiment": "Equipement d'échecs",
"Committees": "Commissions",
"Competitions": "Compétitions",
"ELO processing": "Traitement ELO",
"Email addresses": "Adresses e-mail",
"G License": "Licence G",
"Home": "Accueil",
"Internal rules": "Règlement interne",
"International": "International",
"International competitions": "Compétitions internationales",
"read more": "en savoir plus",
"Regional": "Régional",
"Reports": "Procès verbaux",
"Results SWAR": "Résultats SWAR",
"Statutes": "Statuts",
"Tools": "Outils",
"Tournament rules": "Règlement des tournois",
"Useful information": "Information utile",
"Youth": "Jeiunesse",
}
export default fr