const nl = {
"Administration": "Beheer",
"BC Adults": "BK volwassenen",
"BC Blitz": "BK Blitz",
"BC Rapid": "BK Rapid",
"BC School chess": "BC Schoolschaak",
"BC Youth": "BK Jeugd",
"Board": "Bestuur",
"Chess equiment": "Schaakmateriaal",
"Committees": "Commissies",
"Competitions": "Competities",
"ELO processing": "ELO-verwderking",
"Email addresses": "E-mailadressen",
"G License": "G Licentie",
"Home": "Home",
"Internal rules": "Intern reglement",
"International": "Internationaal",
"International competitions": "Internationale competities",
"read more": "lees meer",
"Regional": "Regionaal",
"Reports": "Verslagen",
"Results SWAR": "Resulaten SWAR",
"Statutes": "Statuten",
"Tools": "Tools",
"Tournament rules": "Wedstrijdreglement",
"Useful information": "Nuttige informatie",
"Youth": "Jeugd",
}
export default nl