const nl = {
"<p>If your are an affilated player you can buy the book 100 years of Belgianchess history for the low price of 10 Euro. Non affilated persons can buy the book for 15 Euro.</p> <p>The book is available in 3 languages:  Dutch, French and German.</p><p>If you are an affiliated player, don't forget to provide your RBCF ID and to click on the search button.  Your name will be filled in automatically</p>": "<p> Als je een aangesloten speler bent, kun je het boek 100 jaar Belgisch schaakgeschiedenis voor de lage prijs van 10 euro kopen. Niet-aangesloten personen kunnen kopen het boek voor 15 euro. </p><p> Het boek is beschikbaar in 3 talen: Nederlands, Frans en Duits. </p><p> Als u een aangesloten speler bent, vergeet dan niet uwstamnummer in te vullen en om op de zoekknop te klikken. Uw naam wordt dan ingevuld automatisch </p>",
"<p>In a few minutes you will receive an confirmation e-mail for your order.The e-mail will include the payment instructions.</p><p>If you selected one of the board members for the delivery, you will find the contact details in this e-mail.</p>": "<p> Binnen enkele minuten ontvang je een bevestigingsmail voor je bestelling.  De e-mail bevat de betalingsinstructies. </p><p> Als je een van de bestuursleden hebt geselecteerd voor de levering, doe je dat vind de contactgegevens in deze e-mail. </p>  ",
"<p>In order to keep the costs low, you can pick the books from 5 members of the board.  You have to contact that person and agree on where and when the book can be handed over.</p><p>The board members are:</p><ul><li>Luc Cornet, covering provinces of Limburg and Liège<li>Bernard Malfliet, covering provinces of Oost-Vlaanderen cost, and Vlaams Brabant<li>Ruben Decrop, covering provinces of Antwerp and West-Vlaanderen<li>Philippe Vukojevic, covering provinces of Namur and Luxembourg<li>Laurent Wery, covering Brussels and provinces of Hainaut and Brabant Wallon</ul><p>See the <a href='/page/board'>Board page</a> for the contact details.</p> <p>Alternatively we can deliver the book at any address in Belgium by DPD at an additional cost of 6.20 Euro </p>": "<p> Om de kosten laag te houden, kunt u de boeken afhaken bij 5 bestuursleden. U moet contact opnemen met die persoon en afspreken waar en wanneer het boek kan worden overhandigd. </p> <p> De bestuursleden zijn: </p> <ul> <li> Luc Cornet, in de provincies Limburg en Luik <li> Bernard Malfliet, die de provincies Oost-Vlaanderen bestrijkt, en Vlaams Brabant <li> Ruben Decrop, die de provincies Antwerpen en West-Vlaanderen bestrijkt <li> Philippe Vukojevic, die de provincies Namen en Luxemburg bestrijkt <li> Laurent Wery, die Brussel en provincies Henegouwen en Waals-Brabant </ul> <p> Zie de <a href='/page/board'> bestuurspagina </a> voor de contactgegevens. </p> <p> Als alternatief kunnen we het boek naar elk adres in België door DPD laten leveren tegen een meerprijs van 6,20 euro </p>",
"Address": "Adres",
"Administration": "Beheer",
"BC Adults": "BK volwassenen",
"BC Blitz": "BK Blitz",
"BC Rapid": "BK Rapid",
"BC School chess": "BC Schoolschaak",
"BC Youth": "BK Jeugd",
"Board": "Bestuur",
"Board members": "Bestuursleden",
"Chess equiment": "Schaakmateriaal",
"Committees": "Commissies",
"Competitions": "Competities",
"Confirm": "Bevestigen",
"Contact details": "Contactdetails",
"Cost": "Kost",
"Delivery": "Levering",
"Distribution points": "Verdeelpunten",
"Dutch": "Nederlands",
"E-mail": "E-mail",
"ELO processing": "ELO-verwderking",
"Email addresses": "E-mailadressen",
"First name": "Voornaam",
"French": "Frans",
"G License": "G Licentie",
"German": "Duits",
"Home": "Home",
"ID RBCF": "Stamnummer KBSB",
"Identity": "Identiteit",
"Internal rules": "Intern reglement",
"International": "Internationaal",
"International competitions": "Internationale competities",
"Last name": "Familienaam",
"Mandated persons": "Gemandateerden",
"Mobile phone": "GSM",
"Ordering form": "Bestelformulier",
"Ordering the book 100 years of Belgian chess history": "Bestellen boek 100 jaar Belgische schaakgeschiedenis",
"read more": "lees meer",
"Regional": "Regionaal",
"Reports": "Verslagen",
"Results SWAR": "Resulaten SWAR",
"Statutes": "Statuten",
"Tools": "Tools",
"Tournament rules": "Wedstrijdreglement",
"Useful information": "Nuttige informatie",
"Which versions do you want?": "Welke versies wens je?",
"Youth": "Jeugd",
}
export default nl