const nl = {
"<p>If your are an affilated player you can buy the book 100 years of Belgianchess history for the low price of 10 Euro. Non affilated persons can buy the book for 15 Euro.</p> <p>The book is available in 3 languages:  Dutch, French and German.</p><p>If you are an affiliated player, don't forget to provide your RBCF ID and to click on the search button.  Your name will be filled in automatically</p>": "<p> Als je een aangesloten speler bent, kun je het boek 100 jaar Belgisch schaakgeschiedenis voor de lage prijs van 10 euro kopen. Niet-aangesloten personen kunnen het boek kopen voor 15 euro. </p><p> Het boek is beschikbaar in 3 talen: Nederlands, Frans en Duits. </p><p> Als u een aangesloten speler bent, vergeet dan niet uw stamnummer in te vullen en om op de zoekknop te klikken. Uw naam wordt dan automatisch ingevuld. </p>",
"<p>In a few minutes you will receive an confirmation e-mail for your order.The e-mail will include the payment instructions.</p><p>If you selected one of the board members for the delivery, you will find the contact details in this e-mail.</p>": "<p> Binnen enkele minuten ontvang je een bevestigingsmail voor je bestelling.  De e-mail bevat de betalingsinstructies. </p><p> Als je een van de bestuursleden hebt geselecteerd voor de levering, doe je dat vind de contactgegevens in deze e-mail. </p>  ",
"<p>In order to keep the costs low, you can pick the books from 1 of the 7 people listed below.</p><ul><li>Luc Cornet, covering provinces of Limburg and Liège<li>Bernard Malfliet, covering provinces of Oost-Vlaanderen and Vlaams Brabant<li>Ruben Decrop, covering provinces of Antwerpen and West-Vlaanderen<li>Philippe Vukojevic, covering provinces of Namur and Luxembourg<li>Laurent Wery, covering provinces of Hainaut and Brabant Wallon<li>Günter Delhaes, covering the German speaking region, reachable at <a href='mailto:delhaes.g@skynet.be'>delhaes.g@skynet.be</a><li>Frank Hoffmeister, covering Brussels, reachable at <a href='mailto:Frank.HOFFMEISTER@ec.europa.eu'>Frank.HOFFMEISTER@ec.europa.eu</a></ul><p>You have to contact that person and agree on where and when the book can be handed over.  See the <a href='/page/board'>Board page</a> for the contact details of the board members.</p> <p>Alternatively we can deliver the book at any address in Belgium by DPD at an additional cost of 6.20 Euro </p>": "<p> Om de kosten laag te houden, kunt u de boeken kiezen bij 1 van de 7 hieronder vermelde personen. </p> <ul> <li> Luc Cornet, die de provincies Limburg en Luik bestrijkt <li> Bernard Malfliet, voor de provincies Oost-Vlaanderen en Vlaams-Brabant <li> Ruben Decrop, voor de provincies Antwerpen en West-Vlaanderen <li> Philippe Vukojevic, voor de provincies Namen en Luxemburg <li> Laurent Wery, voor de provincies Henegouwen en Waals-Brabant <li > Günter Delhaes, voor het Duitstalige gebied, bereikbaar op <a href='mailto:delhaes.g@skynet.be'> delhaes.g@skynet.be </a> <li> Frank Hoffmeister, vanuit Brussel, bereikbaar op <a href='mailtoFrank.HOFFMEISTER@ec.europa.eu'> Frank.HOFFMEISTER@ec.europa.eu </a> </ul> <p> U moet contact opnemen met die persoon en afspreken waar en wanneer het boek kan worden overgedragen. Zie de <a href='/page/board'> Bestuurspagina </a> voor de contactgegevens van de bestuursleden. </p> <p> Als alternatief kunnen we het boek op elk adres in België bezorgen door DPD op een meerprijs van 6,20 euro </p>",
"Address": "Adres",
"Administration": "Beheer",
"BC Adults": "BK volwassenen",
"BC Blitz": "BK Blitz",
"BC Rapid": "BK Rapid",
"BC School chess": "BC Schoolschaak",
"BC Youth": "BK Jeugd",
"Board": "Bestuur",
"Board members": "Bestuursleden",
"Book 100 years": "Boek 100 jaar",
"Chess equiment": "Schaakmateriaal",
"Committees": "Commissies",
"Competitions": "Competities",
"Confirm": "Bevestigen",
"Contact details": "Contactdetails",
"Cost": "Kost",
"Delivery": "Levering",
"Distribution points": "Verdeelpunten",
"Dutch": "Nederlands",
"E-mail": "E-mail",
"ELO processing": "ELO-verwerking",
"Email addresses": "E-mailadressen",
"First name": "Voornaam",
"French": "Frans",
"G License": "G Licentie",
"German": "Duits",
"Home": "Home",
"ID RBCF": "Stamnummer KBSB",
"Identity": "Identiteit",
"Internal rules": "Intern reglement",
"International": "Internationaal",
"International competitions": "Internationale competities",
"Last name": "Familienaam",
"Mandated persons": "Gemandateerden",
"Mobile phone": "GSM",
"Order created successfully": "Bestelling succesvol aangemaakt",
"Ordering form": "Bestelformulier",
"Ordering the book 100 years of Belgian chess history": "Bestellen boek 100 jaar Belgische schaakgeschiedenis",
"Questions": "Vragen",
"read more": "lees meer",
"Regional": "Regionaal",
"Reports": "Verslagen",
"Results SWAR": "Resulaten SWAR",
"Statutes": "Statuten",
"Tools": "Tools",
"Tournament rules": "Wedstrijdreglement",
"Useful information": "Nuttige informatie",
"Which versions do you want?": "Welke versies wens je?",
"Youth": "Jeugd",
}
export default nl