#!/bin/bash
pushd kbsb_backend
python3 -m venv .venv
source .venv/bin/activate
pip install -U pip-tools
pip-compile requirements.in
pip-compile requirements-dev.in
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -e kbsb
popd