---
services:
  db:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  seeddb:
    build:
      context: ./shared/db
    depends_on:
      - db
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    container_name: frontend
    ports:
      - "3000:3000"
