# build the core container with all dependencies
FROM python:3.11
RUN pip install poetry
WORKDIR /app
COPY backend/pyproject.toml ./backend/pyproject.toml
COPY backend/libs ./backend/libs/
WORKDIR /app/backend
RUN poetry install
COPY backend .
COPY shared ../shared
CMD ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "kbsb.main:app"] 