# Generated by Django 2.1.8 on 2019-05-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbDocGroupView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kbsbdoc_kbsbdocgroupview', serialize=False, to='cms.CMSPlugin')),
                ('category', models.CharField(choices=[('', 'Tous - Alle'), ('ca-rvb', "Conseil d'Administration - Raad van Bestuur"), ('ag-av', 'Assemblée générale - Algemene vergadering'), ('cis', 'CIS arbitres - scheidsrechters'), ('dispute', 'Comité de litiges - Geschillencommissie'), ('appeal', "Comité d'appel - Beroepscommissie"), ('other', 'Autre - Andere')], max_length=40, verbose_name='Event')),
                ('topic', models.CharField(choices=[('', 'Tous - Alle'), ('report', 'Rapport - Verslag'), ('invitation', 'Invitation - Uitnodiging'), ('annex', 'Ficher en annexe - Bestand in bijlage'), ('other', 'Autre - Andere')], max_length=40, verbose_name='Topic')),
                ('doctype', models.CharField(choices=[('', 'Tous - Alle'), ('docx', 'Ms Word  file'), ('xlsx', 'Ms Excel file'), ('pptx', 'Ms Powerpoint file'), ('odt', 'Libreoffice writer file'), ('ods', 'Libreoffice calc file'), ('odp', 'Libreoffice impress file'), ('pdf', 'PDF file'), ('md', 'Markdown file'), ('zip', 'Zip file'), ('other', 'Autre - Andere')], max_length=40, verbose_name='Document type')),
                ('year', models.IntegerField(default=2019, verbose_name='Year')),
                ('locale', models.CharField(choices=[('nl', 'nl'), ('fr', 'fr'), ('de', 'de'), ('en', 'en'), ('fr-nl', 'français + nederlands'), ('other', 'Autre - Andere')], max_length=5, verbose_name='Language')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('start', models.IntegerField(default=0, verbose_name='Start index Document')),
                ('count', models.IntegerField(default=25, verbose_name='Number of documents')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='KbsbDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('category', models.CharField(max_length=40)),
                ('doclength', models.IntegerField(verbose_name='Length')),
                ('doctype', models.CharField(max_length=40)),
                ('locale', models.CharField(max_length=5, verbose_name='Locale')),
                ('mimetype', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('topic', models.CharField(max_length=40)),
                ('topicdate', models.DateField(null=True, verbose_name='Topic date')),
                ('uploaded', models.DateTimeField(null=True, verbose_name='Upload date')),
            ],
        ),
    ]
