# Generated by Django 2.1.8 on 2019-05-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('category', models.CharField(max_length=40)),
                ('doclength', models.IntegerField(verbose_name='Length')),
                ('doctype', models.CharField(max_length=40)),
                ('locale', models.CharField(max_length=5, verbose_name='Locale')),
                ('mimetype', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('topic', models.CharField(max_length=40)),
                ('topicdate', models.DateField(null=True, verbose_name='Topic date')),
                ('uploaded', models.DateTimeField(null=True, verbose_name='Upload date')),
            ],
        ),
    ]
