# Generated by Django 2.1.8 on 2019-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbsbdocument',
            name='category',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='kbsbdocument',
            name='doctype',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='kbsbdocument',
            name='mimetype',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='kbsbdocument',
            name='topic',
            field=models.CharField(max_length=80),
        ),
    ]
