# Generated by Django 2.1.8 on 2019-05-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('kbsbdoc', '0002_auto_20190522_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbDocGroupView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kbsbdoc_kbsbdocgroupview', serialize=False, to='cms.CMSPlugin')),
                ('grouptitle', models.CharField(max_length=80, verbose_name='Group title')),
                ('category', models.CharField(choices=[('', 'Tous - Alle'), ('ca-rvb', "Conseil d'Administration - Raad van Bestuur"), ('ag-av', 'Assemblée générale - Algemene vergadering'), ('cis', 'CIS arbitres - scheidsrechters'), ('dispute', 'Comité de litiges - Geschillencommissie'), ('appeal', "Comité d'appel - Beroepscommissie"), ('other', 'Autre - Andere')], max_length=40, verbose_name='Event')),
                ('topic', models.CharField(choices=[('', 'Tous - Alle'), ('report', 'Rapport - Verslag'), ('invitation', 'Invitation - Uitnodiging'), ('annex', 'Ficher en annexe - Bestand in bijlage'), ('other', 'Autre - Andere')], max_length=40, verbose_name='Topic')),
                ('doctype', models.CharField(choices=[('', 'Tous - Alle'), ('docx', 'Ms Word  file'), ('xlsx', 'Ms Excel file'), ('pptx', 'Ms Powerpoint file'), ('odt', 'Libreoffice writer file'), ('ods', 'Libreoffice calc file'), ('odp', 'Libreoffice impress file'), ('pdf', 'PDF file'), ('md', 'Markdown file'), ('zip', 'Zip file'), ('other', 'Autre - Andere')], max_length=40, verbose_name='Document type')),
                ('locale', models.CharField(choices=[('', 'Tous - Alle'), ('nl', 'nl'), ('fr', 'fr'), ('de', 'de'), ('en', 'en'), ('fr-nl', 'français + nederlands'), ('other', 'Autre - Andere')], max_length=5, verbose_name='Language')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
