# Generated by Django 2.1.8 on 2019-05-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbdoc', '0003_kbsbdocgroupview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbsbdocgroupview',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Tous - Alle'), ('ca-rvb', "Conseil d'Administration - Raad van Bestuur"), ('ag-av', 'Assemblée générale - Algemene vergadering'), ('cis', 'CIS arbitres - scheidsrechters'), ('dispute', 'Comité de litiges - Geschillencommissie'), ('appeal', "Comité d'appel - Beroepscommissie"), ('other', 'Autre - Andere')], max_length=40, verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='kbsbdocgroupview',
            name='doctype',
            field=models.CharField(blank=True, choices=[('', 'Tous - Alle'), ('docx', 'Ms Word  file'), ('xlsx', 'Ms Excel file'), ('pptx', 'Ms Powerpoint file'), ('odt', 'Libreoffice writer file'), ('ods', 'Libreoffice calc file'), ('odp', 'Libreoffice impress file'), ('pdf', 'PDF file'), ('md', 'Markdown file'), ('zip', 'Zip file'), ('other', 'Autre - Andere')], max_length=40, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='kbsbdocgroupview',
            name='locale',
            field=models.CharField(blank=True, choices=[('', 'Tous - Alle'), ('nl', 'nl'), ('fr', 'fr'), ('de', 'de'), ('en', 'en'), ('fr-nl', 'français + nederlands'), ('other', 'Autre - Andere')], max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='kbsbdocgroupview',
            name='topic',
            field=models.CharField(blank=True, choices=[('', 'Tous - Alle'), ('report', 'Rapport - Verslag'), ('invitation', 'Invitation - Uitnodiging'), ('annex', 'Ficher en annexe - Bestand in bijlage'), ('other', 'Autre - Andere')], max_length=40, verbose_name='Topic'),
        ),
    ]
