# Generated by Django 2.1.8 on 2019-06-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('kbsbdoc', '0004_auto_20190524_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbPhpLinkView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kbsbdoc_kbsbphplinkview', serialize=False, to='cms.CMSPlugin')),
                ('url', models.CharField(max_length=80, verbose_name='Url')),
                ('label', models.CharField(max_length=80, verbose_name='Label')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
