# Generated by Django 2.1.8 on 2019-05-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('kbsbarticles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbMarkdownView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kbsbarticles_kbsbmarkdownview', serialize=False, to='cms.CMSPlugin')),
                ('source', models.TextField(verbose_name='Markdown source')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
