# Generated by Django 2.1.8 on 2019-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbarticles', '0002_kbsbmarkdownview'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbsbmarkdownview',
            name='sanitize',
            field=models.BooleanField(default=True, verbose_name='Sanitize html'),
        ),
    ]
