# Generated by Django 2.1.8 on 2019-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbarticles', '0002_auto_20190426_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbsbarticle',
            name='endpublication',
        ),
        migrations.RemoveField(
            model_name='kbsbarticle',
            name='startpublication',
        ),
        migrations.RemoveField(
            model_name='kbsbarticle',
            name='status',
        ),
        migrations.AddField(
            model_name='kbsbarticle',
            name='archived',
            field=models.DateTimeField(null=True, verbose_name='Archive date'),
        ),
        migrations.AddField(
            model_name='kbsbarticle',
            name='published',
            field=models.DateTimeField(null=True, verbose_name='Publication date'),
        ),
    ]
