# Generated by Django 2.1.8 on 2019-05-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('kbsbarticles', '0003_kbsbmarkdownview_sanitize'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbArticlesIntroView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kbsbarticles_kbsbarticlesintroview', serialize=False, to='cms.CMSPlugin')),
                ('start', models.IntegerField(verbose_name='Start number article')),
                ('count', models.IntegerField(verbose_name='Number of articles')),
                ('locale', models.CharField(max_length=5, verbose_name='Locale')),
                ('ss', models.CharField(max_length=80, verbose_name='Search String')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
