# Generated by Django 2.1.8 on 2019-05-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbarticles', '0004_kbsbarticlesintroview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbsbarticlesintroview',
            name='ss',
        ),
    ]
