# Generated by Django 2.1.8 on 2019-05-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbarticles', '0005_remove_kbsbarticlesintroview_ss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbsbarticlesintroview',
            name='locale',
        ),
    ]
