export default {
  catchoices: [
    {value: 'ca-rvb', text: "Conseil d'Administration - Raad van Bestuur"},
    {value: 'ag-av', text: "Assemblée générale - Algemene vergadering"},
    {value: 'cis', text: "CIS arbitres - scheidsrechters"},
    {value: 'dispute', text: "Comité de litiges - Geschillencommissie"},
    {value: 'appeal', text: "Comité d'appel - Beroepscommissie"},
    {value: 'other', text: "Autre - Andere"},
  ],
  doctypechoices: [
    {value: 'pdf', text: 'PDF file'},
    {value: 'docx', text:'Ms Word docx file'},
    {value: 'xlsx', text: 'Ms Excel xlsx file'},
    {value: 'pptx', text: 'Ms Powerpoint pptx file'},
    {value: 'odt', text: 'Libreoffice writer file'},
    {value: 'ods', text: 'Libreoffice calc file'},
    {value: 'odp', text: 'Libreoffice impress file'},
    {value: 'txt', text: 'Text file'},
    {value: 'md', text: 'Markdown file'},
    {value: 'zip', text: 'Zip file'},
    {value: 'other', text: 'Autre - Andere'},
  ],
  localechoices: [
    {value: 'nl', text: 'nl'},
    {value: 'fr', text: 'fr'},
    {value: 'de', text: 'de'},
    {value: 'en', text: 'en'},
    {value: 'fr-nl', text: 'fr + nl'},
    {value: 'other', text: 'Autre - Andere'},
  ],
  topicchoices: [
    {value: 'report', text: 'Rapport - Verslag'},
    {value: 'invitation', text: 'Invitation - Uitnodiging'},
    {value: 'annex', text: 'Ficher en annexe - Bestand in bijlage'},
    {value: 'other', text: 'Autre - Andere'},
  ],  
}