# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdTranslationAvailable',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cd_i18n_cdtranslationavailable', serialize=False, to='cms.CMSPlugin')),
                ('nl', models.BooleanField(default=False)),
                ('fr', models.BooleanField(default=False)),
                ('en', models.BooleanField(default=False)),
                ('de', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
