# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_i18n', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtranslationavailable',
            name='de',
            field=models.BooleanField(default=False, verbose_name='German version available'),
        ),
        migrations.AlterField(
            model_name='cdtranslationavailable',
            name='en',
            field=models.BooleanField(default=False, verbose_name='English version available'),
        ),
        migrations.AlterField(
            model_name='cdtranslationavailable',
            name='fr',
            field=models.BooleanField(default=False, verbose_name='French version available'),
        ),
        migrations.AlterField(
            model_name='cdtranslationavailable',
            name='nl',
            field=models.BooleanField(default=False, verbose_name='Dutch version available'),
        ),
    ]
