---
# tasks for setting up local application
- hosts: localhost
  tasks:

    - name: setup docker networking for web
      docker_network:
        name: webnet

    - name: create volume for application source
      docker_volume:
        name: kbsb_src

    - name: Install APT Requirements
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git

    - name: checkout
      git:
        name: https://github.com/cropr/kbsb.git
        dest: kbsb

    - name:
      docker_image:
        name: kbsb_app
        path: .
