---
# tasks setting up database

- hosts: localhost
  tasks:

    - name: setup docker networking for postgres
      docker_network:
        name: pgnet

    - name: create volume for postgres data
      docker_volume:
        name: pgdata

    - name: launch database container
      docker_container:
        name: pg
        image: postgres
        state: started
        ports:
         - "5432:5432"
        volumes:
          - "pgdata:/var/lib/postgresql/data"
        networks:
          - name: pgnet

    - name: create database user
      postgresql_user:
        login_host: 127.0.0.1
        name: ruben
        encrypted: yes
        password: wz1knbg
        role_attr_flags: CREATEDB,NOSUPERUSER

    - name: create kbsb database
      postgresql_db:
        login_host: 127.0.0.1
        login_user: ruben
        login_password: wz1knbg
        name: kbsb
        owner: ruben
