---
# tasks for setting up portainer

- hosts: localhost
  tasks:

    - name: create volume for portainer data
      docker_volume:
        name: portainer_data

    - name: launch portainer container
      docker_container:
        name: portainer
        image: portainer/portainer
        state: started
        restart_policy: always
        ports:
         - "9000:9000"
        volumes:
          - "portainer_data:/data"
          - "/var/run/docker.sock:/var/run/docker.sock"
