# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  required_plugins = %w( vagrant-vbguest vagrant-disksize )
  _retry = false
  required_plugins.each do |plugin|
      unless Vagrant.has_plugin? plugin
          system "vagrant plugin install #{plugin}"
          _retry=true
      end
  end

  if (_retry)
      exec "vagrant " + ARGV.join(' ')
  end

  config.disksize.size = "20GB"

  config.vm.define "node01" do |node01|
    node01.vm.box = "ubuntu/xenial64"
    node01.vm.hostname = 'node01'
    node01.vm.network :forwarded_port, guest: 22, host: 2022, id: "ssh"
    # all ports in local are set in the 81xx range on the host
    node01.vm.network :forwarded_port, guest: 8000, host: 8100
    node01.vm.network :forwarded_port, guest: 9000, host: 8101
    node01.vm.network :forwarded_port, guest: 5432, host: 8132
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git build-essential python2.7 python-simplejson python-pip openssl libssl-dev ca-certificates apt-transport-https curl
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository -y \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"
    apt-get update
    apt-get install -y docker-ce
    pip install --upgrade pip
    pip install docker-compose
    pip install psycopg2.binary
    pip install ansible
    pip install pyopenssl
    usermod -aG docker vagrant
  SHELL
end
