# Generated by Django 2.1.8 on 2019-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeimage', models.BinaryField(blank=True, verbose_name='Badge image')),
                ('badgelength', models.IntegerField(blank=True, default=0, verbose_name='Length badge image')),
                ('badgemimetype', models.CharField(blank=True, default='', max_length=20, verbose_name='Badge mimetype')),
                ('birthdate', models.DateField(null=True, verbose_name='Birthdate')),
                ('chesstitle', models.CharField(blank=True, default='', max_length=4, verbose_name='Chess title')),
                ('email', models.CharField(blank=True, default='', max_length=40, verbose_name='Email')),
                ('federation', models.CharField(blank=True, max_length=4, verbose_name='Federation')),
                ('first_name', models.CharField(max_length=25, verbose_name='First name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('idclub', models.CharField(blank=True, max_length=4, verbose_name='Club id')),
                ('idfide', models.CharField(blank=True, max_length=15, verbose_name='FIDE id')),
                ('idbel', models.CharField(max_length=6, unique=True, verbose_name='Belgian id')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last name')),
                ('locale', models.CharField(max_length=5, verbose_name='Locale')),
                ('mobiletel', models.CharField(blank=True, default='', max_length=15, verbose_name='Mobile phone')),
                ('nationalitybel', models.CharField(blank=True, max_length=4, verbose_name='Nationality on passport')),
                ('nationalityfide', models.CharField(blank=True, max_length=4, verbose_name='Nationality for FIDE')),
                ('privacy', models.TextField(default='{}', verbose_name='Privacy Restrictions')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('roles', models.TextField(default='{}', verbose_name='Roles')),
            ],
        ),
    ]
