# Generated by Django 2.1.8 on 2019-06-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbGroupNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=25, verbose_name='Abbreviated group name')),
                ('name', models.CharField(max_length=80, verbose_name='Long group name')),
                ('translations', models.TextField(verbose_name='Translations (JSON)')),
            ],
        ),
        migrations.CreateModel(
            name='KbsbGroupView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kbsbmembers_kbsbgroupview', serialize=False, to='cms.CMSPlugin')),
                ('groupname', models.CharField(max_length=25, verbose_name='Group name')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='KbsbMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeimage', models.BinaryField(blank=True, verbose_name='Badge image')),
                ('badgelength', models.IntegerField(blank=True, default=0, verbose_name='Length badge image')),
                ('badgemimetype', models.CharField(blank=True, default='', max_length=20, verbose_name='Badge mimetype')),
                ('birthdate', models.DateField(null=True, verbose_name='Birthdate')),
                ('chesstitle', models.CharField(blank=True, default='', max_length=4, verbose_name='Chess title')),
                ('email', models.CharField(blank=True, default='', max_length=40, verbose_name='Email')),
                ('federation', models.CharField(blank=True, max_length=4, verbose_name='Federation')),
                ('first_name', models.CharField(max_length=25, verbose_name='First name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('idclub', models.CharField(blank=True, max_length=4, verbose_name='Club id')),
                ('idfide', models.CharField(blank=True, max_length=15, verbose_name='FIDE id')),
                ('idbel', models.CharField(max_length=6, unique=True, verbose_name='Belgian id')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last name')),
                ('locale', models.CharField(max_length=5, verbose_name='Locale')),
                ('mobiletel', models.CharField(blank=True, default='', max_length=15, verbose_name='Mobile phone')),
                ('nationalitybel', models.CharField(blank=True, max_length=4, verbose_name='Nationality on passport')),
                ('nationalityfide', models.CharField(blank=True, max_length=4, verbose_name='Nationality for FIDE')),
                ('privacy', models.TextField(default='{}', verbose_name='Privacy Restrictions (JSON)')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('roles', models.TextField(default='{}', verbose_name='Roles (JSON)')),
            ],
        ),
        migrations.CreateModel(
            name='KbsbMemberView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kbsbmembers_kbsbmemberview', serialize=False, to='cms.CMSPlugin')),
                ('idbel', models.CharField(max_length=6, verbose_name='Belgian id')),
                ('groupname', models.CharField(max_length=25, verbose_name='Group name')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='KbsbRoleNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=25, verbose_name='Abbreviated role name')),
                ('name', models.CharField(max_length=80, verbose_name='Long role name ')),
                ('translations', models.TextField(verbose_name='Translations (JSON)')),
            ],
        ),
    ]
