# Generated by Django 2.1.8 on 2019-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbmembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbsbmember',
            name='privacy',
            field=models.CharField(default='', max_length=255, verbose_name='Privacy Restrictions'),
        ),
    ]
