# Generated by Django 2.1.8 on 2019-05-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbmembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbGroupNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=10, verbose_name='Abbreviated group name')),
                ('name', models.CharField(max_length=80, verbose_name='Long group name')),
                ('translations', models.TextField(verbose_name='Translations (JSON)')),
            ],
        ),
        migrations.CreateModel(
            name='KbsbRoleNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=10, verbose_name='Abbreviated role name')),
                ('en_name', models.CharField(max_length=40, verbose_name='Long role name ')),
                ('translations', models.TextField(verbose_name='Translations (JSON)')),
            ],
        ),
        migrations.AlterField(
            model_name='kbsbmember',
            name='privacy',
            field=models.TextField(default='{}', verbose_name='Privacy Restrictions (JSON)'),
        ),
        migrations.AlterField(
            model_name='kbsbmember',
            name='roles',
            field=models.TextField(default='{}', verbose_name='Roles (JSON)'),
        ),
    ]
