# Generated by Django 2.1.8 on 2019-06-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbmembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbsbgroupview',
            name='groupname',
            field=models.CharField(choices=[('-', '-')], max_length=25, verbose_name='Group name'),
        ),
        migrations.AlterField(
            model_name='kbsbmemberview',
            name='groupname',
            field=models.CharField(choices=[('-', '-')], max_length=25, verbose_name='Group name'),
        ),
    ]
