# Generated by Django 2.1.8 on 2019-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbsbmembers', '0002_auto_20190505_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbsbrolenames',
            name='en_name',
        ),
        migrations.AddField(
            model_name='kbsbrolenames',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='Long role name '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kbsbgroupnames',
            name='shortname',
            field=models.CharField(max_length=25, verbose_name='Abbreviated group name'),
        ),
        migrations.AlterField(
            model_name='kbsbrolenames',
            name='shortname',
            field=models.CharField(max_length=25, verbose_name='Abbreviated role name'),
        ),
    ]
