# Generated by Django 2.1.8 on 2019-05-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('kbsbmembers', '0002_kbsbmemberview'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbsbGroupView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kbsbmembers_kbsbgroupview', serialize=False, to='cms.CMSPlugin')),
                ('groupname', models.CharField(choices=[('Board', 'Members of the board'), ('Dispute', 'Commission for disputes'), ('VSF', 'Vlaamse Schaakfederatie'), ('Appeal', 'Members of appeal commission')], max_length=25, verbose_name='Group name')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='kbsbmemberview',
            name='groupname',
            field=models.CharField(choices=[('Board', 'Members of the board'), ('Dispute', 'Commission for disputes'), ('VSF', 'Vlaamse Schaakfederatie'), ('Appeal', 'Members of appeal commission')], max_length=25, verbose_name='Group name'),
        ),
    ]
