# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdTranslationAvailable',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cd_plugins_cdtranslationavailable', serialize=False, to='cms.CMSPlugin')),
                ('nl', models.BooleanField(default=False, verbose_name='Dutch version available')),
                ('fr', models.BooleanField(default=False, verbose_name='French version available')),
                ('de', models.BooleanField(default=False, verbose_name='German version available')),
                ('en', models.BooleanField(default=False, verbose_name='English version available')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
